@server = https://ominous-doodle-6jq6gv4g4rvf9j4-8080.app.github.dev
###
GET {{server}}/api/instrumentos/2
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "Viento", "descripcion": "Como una flauta"}
###
GET {{server}}/api/musicos
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Joaquín"}
###
GET {{server}}/api/bandas
###
GET {{server}}/api/bandas/1
###
GET {{server}}/api/bandas/1/formacion
###
GET {{server}}/api/categorias
###
GET {{server}}/api/productos/formacion